# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bd8ae3004278593b57bdbb22d95669bb5708604f42fce053f4b4ce4c95b8d5eed14002b71b2da718b2d455b143240200214e7113f973cab2a97b5efa9ff9363

test:
  secret_key_base: 561a53eca5ed7343ba2dd79123ee924e16724b2dc2b5e58fec99e619f62880d7423079b790aeb8eda22ddd50dd063be23fc9429306d215221ed773392c0c6dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
